// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonCardGrader.Infrastructure.Data;

#nullable disable

namespace PokemonCardGrader.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421122847_AddAnalysisCorrections")]
    partial class AddAnalysisCorrections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.AnalysisCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CardSubmissionId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AnalysisCorrections");
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.CardImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CardSubmissionId");

                    b.ToTable("CardImages");
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.CardSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PokemonCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonCardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardSubmissions");
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.GradeEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("EstimatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRuleBased")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PredictedGrade")
                        .HasColumnType("float");

                    b.Property<string>("SubGrades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardSubmissionId", "Company");

                    b.ToTable("GradeEstimates");
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.GradingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ActualGrade")
                        .HasColumnType("float");

                    b.Property<string>("ActualSubGrades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CardSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CardSubmissionId")
                        .IsUnique();

                    b.HasIndex("Company", "ActualGrade");

                    b.ToTable("GradingResults");
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.PokemonCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsManualEntry")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TcgApiId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SetCode");

                    b.HasIndex("TcgApiId")
                        .IsUnique()
                        .HasFilter("[TcgApiId] IS NOT NULL");

                    b.ToTable("PokemonCards");
                });

            modelBuilder.Entity("PokemonCardGrader.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PokemonCardGrader.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PokemonCardGrader.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonCardGrader.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PokemonCardGrader.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.AnalysisCorrection", b =>
                {
                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.ConditionScores", "CorrectedScores", b1 =>
                        {
                            b1.Property<Guid>("AnalysisCorrectionId");

                            b1.Property<double>("Corners");

                            b1.Property<double>("Edges");

                            b1.Property<double>("Surface");

                            b1.HasKey("AnalysisCorrectionId");

                            b1.ToTable("AnalysisCorrections");

                            b1
                                .ToJson("CorrectedScores")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisCorrectionId");

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.CenteringMeasurement", "Centering", b2 =>
                                {
                                    b2.Property<Guid>("ConditionScoresAnalysisCorrectionId");

                                    b2.Property<double>("LeftRightBack");

                                    b2.Property<double>("LeftRightFront");

                                    b2.Property<double>("TopBottomBack");

                                    b2.Property<double>("TopBottomFront");

                                    b2.HasKey("ConditionScoresAnalysisCorrectionId");

                                    b2.ToTable("AnalysisCorrections");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionScoresAnalysisCorrectionId");
                                });

                            b1.Navigation("Centering")
                                .IsRequired();
                        });

                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.AnalysisOverlay", "OriginalOverlay", b1 =>
                        {
                            b1.Property<Guid>("AnalysisCorrectionId");

                            b1.HasKey("AnalysisCorrectionId");

                            b1.ToTable("AnalysisCorrections");

                            b1
                                .ToJson("OriginalOverlay")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisCorrectionId");

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.BorderLines", "BorderLines", b2 =>
                                {
                                    b2.Property<Guid>("AnalysisOverlayAnalysisCorrectionId");

                                    b2.Property<double>("BottomBorderY");

                                    b2.Property<double>("LeftBorderX");

                                    b2.Property<double>("RightBorderX");

                                    b2.Property<double>("TopBorderY");

                                    b2.HasKey("AnalysisOverlayAnalysisCorrectionId");

                                    b2.ToTable("AnalysisCorrections");

                                    b2.WithOwner()
                                        .HasForeignKey("AnalysisOverlayAnalysisCorrectionId");
                                });

                            b1.OwnsMany("PokemonCardGrader.Domain.ValueObjects.NormalizedPoint", "CardBoundary", b2 =>
                                {
                                    b2.Property<Guid>("AnalysisOverlayAnalysisCorrectionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("AnalysisOverlayAnalysisCorrectionId", "__synthesizedOrdinal");

                                    b2.ToTable("AnalysisCorrections");

                                    b2.WithOwner()
                                        .HasForeignKey("AnalysisOverlayAnalysisCorrectionId");
                                });

                            b1.Navigation("BorderLines")
                                .IsRequired();

                            b1.Navigation("CardBoundary");
                        });

                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.ConditionScores", "OriginalScores", b1 =>
                        {
                            b1.Property<Guid>("AnalysisCorrectionId");

                            b1.Property<double>("Corners");

                            b1.Property<double>("Edges");

                            b1.Property<double>("Surface");

                            b1.HasKey("AnalysisCorrectionId");

                            b1.ToTable("AnalysisCorrections");

                            b1
                                .ToJson("OriginalScores")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisCorrectionId");

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.CenteringMeasurement", "Centering", b2 =>
                                {
                                    b2.Property<Guid>("ConditionScoresAnalysisCorrectionId");

                                    b2.Property<double>("LeftRightBack");

                                    b2.Property<double>("LeftRightFront");

                                    b2.Property<double>("TopBottomBack");

                                    b2.Property<double>("TopBottomFront");

                                    b2.HasKey("ConditionScoresAnalysisCorrectionId");

                                    b2.ToTable("AnalysisCorrections");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionScoresAnalysisCorrectionId");
                                });

                            b1.Navigation("Centering")
                                .IsRequired();
                        });

                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.UserCorrection", "Correction", b1 =>
                        {
                            b1.Property<Guid>("AnalysisCorrectionId");

                            b1.Property<Guid>("CardImageId");

                            b1.PrimitiveCollection<string>("DismissedDefectIndices")
                                .IsRequired();

                            b1.HasKey("AnalysisCorrectionId");

                            b1.ToTable("AnalysisCorrections");

                            b1
                                .ToJson("Correction")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisCorrectionId");

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.BorderLines", "AdjustedBorders", b2 =>
                                {
                                    b2.Property<Guid>("UserCorrectionAnalysisCorrectionId");

                                    b2.Property<double>("BottomBorderY");

                                    b2.Property<double>("LeftBorderX");

                                    b2.Property<double>("RightBorderX");

                                    b2.Property<double>("TopBorderY");

                                    b2.HasKey("UserCorrectionAnalysisCorrectionId");

                                    b2.ToTable("AnalysisCorrections");

                                    b2.WithOwner()
                                        .HasForeignKey("UserCorrectionAnalysisCorrectionId");
                                });

                            b1.OwnsMany("PokemonCardGrader.Domain.ValueObjects.NormalizedPoint", "AdjustedBoundary", b2 =>
                                {
                                    b2.Property<Guid>("UserCorrectionAnalysisCorrectionId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("UserCorrectionAnalysisCorrectionId", "__synthesizedOrdinal");

                                    b2.ToTable("AnalysisCorrections");

                                    b2.WithOwner()
                                        .HasForeignKey("UserCorrectionAnalysisCorrectionId");
                                });

                            b1.Navigation("AdjustedBorders");

                            b1.Navigation("AdjustedBoundary");
                        });

                    b.Navigation("CorrectedScores")
                        .IsRequired();

                    b.Navigation("Correction")
                        .IsRequired();

                    b.Navigation("OriginalOverlay")
                        .IsRequired();

                    b.Navigation("OriginalScores")
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.CardImage", b =>
                {
                    b.HasOne("PokemonCardGrader.Domain.Entities.CardSubmission", null)
                        .WithMany("Images")
                        .HasForeignKey("CardSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.ImageAnalysisResult", "AnalysisResult", b1 =>
                        {
                            b1.Property<Guid>("CardImageId");

                            b1.Property<string>("AnalysisMethod")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("AnalyzedAt");

                            b1.Property<double?>("CornersScore");

                            b1.Property<double?>("EdgesScore");

                            b1.Property<double?>("SurfaceScore");

                            b1.HasKey("CardImageId");

                            b1.ToTable("CardImages");

                            b1
                                .ToJson("AnalysisResult")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CardImageId");

                            b1.OwnsMany("PokemonCardGrader.Domain.ValueObjects.DetectedDefect", "DetectedDefects", b2 =>
                                {
                                    b2.Property<Guid>("ImageAnalysisResultCardImageId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Confidence");

                                    b2.Property<double>("Height");

                                    b2.Property<double>("Severity");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.Property<double>("Width");

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("ImageAnalysisResultCardImageId", "__synthesizedOrdinal");

                                    b2.ToTable("CardImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageAnalysisResultCardImageId");
                                });

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.CenteringMeasurement", "DetectedCentering", b2 =>
                                {
                                    b2.Property<Guid>("ImageAnalysisResultCardImageId");

                                    b2.Property<double>("LeftRightBack");

                                    b2.Property<double>("LeftRightFront");

                                    b2.Property<double>("TopBottomBack");

                                    b2.Property<double>("TopBottomFront");

                                    b2.HasKey("ImageAnalysisResultCardImageId");

                                    b2.ToTable("CardImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageAnalysisResultCardImageId");
                                });

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.AnalysisOverlay", "Overlay", b2 =>
                                {
                                    b2.Property<Guid>("ImageAnalysisResultCardImageId");

                                    b2.HasKey("ImageAnalysisResultCardImageId");

                                    b2.ToTable("CardImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageAnalysisResultCardImageId");

                                    b2.OwnsOne("PokemonCardGrader.Domain.ValueObjects.BorderLines", "BorderLines", b3 =>
                                        {
                                            b3.Property<Guid>("AnalysisOverlayImageAnalysisResultCardImageId");

                                            b3.Property<double>("BottomBorderY");

                                            b3.Property<double>("LeftBorderX");

                                            b3.Property<double>("RightBorderX");

                                            b3.Property<double>("TopBorderY");

                                            b3.HasKey("AnalysisOverlayImageAnalysisResultCardImageId");

                                            b3.ToTable("CardImages");

                                            b3.WithOwner()
                                                .HasForeignKey("AnalysisOverlayImageAnalysisResultCardImageId");
                                        });

                                    b2.OwnsMany("PokemonCardGrader.Domain.ValueObjects.NormalizedPoint", "CardBoundary", b3 =>
                                        {
                                            b3.Property<Guid>("AnalysisOverlayImageAnalysisResultCardImageId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAddOrUpdate();

                                            b3.Property<double>("X");

                                            b3.Property<double>("Y");

                                            b3.HasKey("AnalysisOverlayImageAnalysisResultCardImageId", "__synthesizedOrdinal");

                                            b3.ToTable("CardImages");

                                            b3.WithOwner()
                                                .HasForeignKey("AnalysisOverlayImageAnalysisResultCardImageId");
                                        });

                                    b2.Navigation("BorderLines")
                                        .IsRequired();

                                    b2.Navigation("CardBoundary");
                                });

                            b1.Navigation("DetectedCentering");

                            b1.Navigation("DetectedDefects");

                            b1.Navigation("Overlay");
                        });

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.CardSubmission", b =>
                {
                    b.HasOne("PokemonCardGrader.Domain.Entities.PokemonCard", "PokemonCard")
                        .WithMany()
                        .HasForeignKey("PokemonCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.ConditionScores", "FinalScores", b1 =>
                        {
                            b1.Property<Guid>("CardSubmissionId");

                            b1.Property<double>("Corners");

                            b1.Property<double>("Edges");

                            b1.Property<double>("Surface");

                            b1.HasKey("CardSubmissionId");

                            b1.ToTable("CardSubmissions");

                            b1
                                .ToJson("FinalScores")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CardSubmissionId");

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.CenteringMeasurement", "Centering", b2 =>
                                {
                                    b2.Property<Guid>("ConditionScoresCardSubmissionId");

                                    b2.Property<double>("LeftRightBack");

                                    b2.Property<double>("LeftRightFront");

                                    b2.Property<double>("TopBottomBack");

                                    b2.Property<double>("TopBottomFront");

                                    b2.HasKey("ConditionScoresCardSubmissionId");

                                    b2.ToTable("CardSubmissions");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionScoresCardSubmissionId");
                                });

                            b1.Navigation("Centering")
                                .IsRequired();
                        });

                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.ConditionScores", "ImageDerivedScores", b1 =>
                        {
                            b1.Property<Guid>("CardSubmissionId");

                            b1.Property<double>("Corners");

                            b1.Property<double>("Edges");

                            b1.Property<double>("Surface");

                            b1.HasKey("CardSubmissionId");

                            b1.ToTable("CardSubmissions");

                            b1
                                .ToJson("ImageDerivedScores")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CardSubmissionId");

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.CenteringMeasurement", "Centering", b2 =>
                                {
                                    b2.Property<Guid>("ConditionScoresCardSubmissionId");

                                    b2.Property<double>("LeftRightBack");

                                    b2.Property<double>("LeftRightFront");

                                    b2.Property<double>("TopBottomBack");

                                    b2.Property<double>("TopBottomFront");

                                    b2.HasKey("ConditionScoresCardSubmissionId");

                                    b2.ToTable("CardSubmissions");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionScoresCardSubmissionId");
                                });

                            b1.Navigation("Centering")
                                .IsRequired();
                        });

                    b.OwnsOne("PokemonCardGrader.Domain.ValueObjects.ConditionScores", "ManualScores", b1 =>
                        {
                            b1.Property<Guid>("CardSubmissionId");

                            b1.Property<double>("Corners");

                            b1.Property<double>("Edges");

                            b1.Property<double>("Surface");

                            b1.HasKey("CardSubmissionId");

                            b1.ToTable("CardSubmissions");

                            b1
                                .ToJson("ManualScores")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CardSubmissionId");

                            b1.OwnsOne("PokemonCardGrader.Domain.ValueObjects.CenteringMeasurement", "Centering", b2 =>
                                {
                                    b2.Property<Guid>("ConditionScoresCardSubmissionId");

                                    b2.Property<double>("LeftRightBack");

                                    b2.Property<double>("LeftRightFront");

                                    b2.Property<double>("TopBottomBack");

                                    b2.Property<double>("TopBottomFront");

                                    b2.HasKey("ConditionScoresCardSubmissionId");

                                    b2.ToTable("CardSubmissions");

                                    b2.WithOwner()
                                        .HasForeignKey("ConditionScoresCardSubmissionId");
                                });

                            b1.Navigation("Centering")
                                .IsRequired();
                        });

                    b.Navigation("FinalScores");

                    b.Navigation("ImageDerivedScores");

                    b.Navigation("ManualScores");

                    b.Navigation("PokemonCard");
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.GradeEstimate", b =>
                {
                    b.HasOne("PokemonCardGrader.Domain.Entities.CardSubmission", null)
                        .WithMany("Estimates")
                        .HasForeignKey("CardSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.GradingResult", b =>
                {
                    b.HasOne("PokemonCardGrader.Domain.Entities.CardSubmission", null)
                        .WithOne("ActualResult")
                        .HasForeignKey("PokemonCardGrader.Domain.Entities.GradingResult", "CardSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonCardGrader.Domain.Entities.CardSubmission", b =>
                {
                    b.Navigation("ActualResult");

                    b.Navigation("Estimates");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
